######################################################################
# Automatically generated by qmake (3.0) Sat Mar 16 12:56:09 2019
######################################################################

TEMPLATE = app
TARGET = gaz
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += gaz.cpp
